import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, Check, ChevronRight, CircleDollarSign, Clock3, Copy, ExternalLink, FileCheck2, LoaderCircle, LockKeyhole, Plus, ShieldCheck, Sparkles, Truck, WalletCards, X} from 'lucide-react';
import './style.css';
import './gallery.css';
import escrowVisual from './assets/hero-escrow.png';
import logisticsVisual from './assets/hero-logistics.png';
import settlementVisual from './assets/hero-settlement.png';
import approvalVisual from './assets/hero-approval.png';
import verificationVisual from './assets/hero-verification.png';

const jobs=[
 {id:'FG-2048', client:'Kora Foods Ltd.', amount:'2,400', milestone:'Cold-chain delivery', status:'Ready to fund', due:'Today, 15:00'},
 {id:'FG-2045', client:'MediBridge', amount:'1,180', milestone:'Verified delivery', status:'In review', due:'Proof received'},
 {id:'FG-2039', client:'Lagos Fresh', amount:'620', milestone:'Released', status:'Complete', due:'Sep 19'}
];
const heroSlides=[
  {image:escrowVisual,label:'USDG ESCROW',caption:'Funds are protected'},
  {image:logisticsVisual,label:'VERIFIED DELIVERY',caption:'Proof follows the work'},
  {image:settlementVisual,label:'INSTANT SETTLEMENT',caption:'Value moves in minutes'},
  {image:approvalVisual,label:'BUYER IN CONTROL',caption:'Release only when ready'},
  {image:verificationVisual,label:'ONCHAIN TRUST',caption:'Every milestone is auditable'}
];
function HeroGallery(){const [active,setActive]=useState(0);useEffect(()=>{const timer=setInterval(()=>setActive(n=>(n+1)%heroSlides.length),4800);return()=>clearInterval(timer)},[]);const slide=heroSlides[active];return <div className="gallery" aria-label="FlowGuard visual story"><img key={slide.image} src={slide.image} alt=""/><div className="galleryShade"/><div className="galleryLabel"><span>{slide.label}</span><b>{slide.caption}</b></div><div className="galleryDots">{heroSlides.map((item,index)=><button key={item.label} className={index===active?'active':''} aria-label={'Show '+item.label} onClick={()=>setActive(index)}/>)}</div></div>}
function DashboardV2(){return <><Top/><main className="dash"><section className="hero"><div><span className="eyebrow">ESCROW FOR REAL-WORLD COMMERCE</span><h1>Payment moves when<br/><em>work is proven.</em></h1><p>FlowGuard protects growing businesses with USDG milestone escrow, verified delivery proof, and fast settlement on Arbitrum.</p><div className="buttonRow"><button className="primary" onClick={()=>go('create')}>Create protected payment <ArrowRight size={17}/></button><button className="secondary">Watch 60 sec demo</button></div></div><HeroGallery/></section><section className="metrics"><div><b>$42,860</b><span>Protected this month</span></div><div><b>98.7%</b><span>Proof approved first time</span></div><div><b>&lt; 2 min</b><span>Settlement time</span></div></section><section className="work"><div className="sectionTitle"><div><span className="eyebrow">YOUR WORKSPACE</span><h2>Protected payments</h2></div><button className="new" onClick={()=>go('create')}><Plus size={17}/> New payment</button></div><div className="jobList">{jobs.map((j,i)=><button className="job" key={j.id} onClick={()=>go(i===0?'fund':i===1?'review':'release')}><div className="avatar">{j.client.slice(0,1)}</div><div className="jobMain"><b>{j.client}</b><span>{j.id} · {j.milestone}</span></div><div className="jobStatus"><span className={'pill p'+i}>{j.status}</span><small>{j.due}</small></div><b className="amount">${j.amount}<small> USDG</small></b><ChevronRight size={19}/></button>)}</div></section></main></>}
const paths={dashboard:'/',create:'/create',fund:'/fund',proof:'/proof',review:'/review',release:'/release',success:'/success',register:'/buildathon'};
function go(name){ history.pushState({},'',paths[name]||'/'); window.dispatchEvent(new Event('popstate')); }
function Top(){return <header><a className="brand" onClick={()=>go('dashboard')}><span className="brandMark">F</span> FLOWGUARD</a><nav><a>How it works</a><a>For businesses</a><a>Security</a></nav><button className="wallet" onClick={()=>go('success')}><WalletCards size={17}/> 0xDami…94F2</button></header>}
function Shell({eyebrow,title,copy,children}){return <><Top/><main className="page"><div className="pageHeading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{copy&&<p>{copy}</p>}</div>{children}</main></>}
function Progress({step}){return <div className="progress">{['Create agreement','Fund in USDG','Verify delivery','Release payment'].map((x,i)=><div className={i<step?'done':i===step?'current':''} key={x}><span>{i<step?<Check size={14}/>:i+1}</span>{x}</div>)}</div>}
function Dashboard(){return <><Top/><main className="dash"><section className="hero"><div><span className="eyebrow">ESCROW FOR REAL-WORLD COMMERCE</span><h1>Payment moves when<br/><em>work is proven.</em></h1><p>FlowGuard protects growing businesses with USDG milestone escrow, verified delivery proof, and fast settlement on Arbitrum.</p><div className="buttonRow"><button className="primary" onClick={()=>go('create')}>Create protected payment <ArrowRight size={17}/></button><button className="secondary">Watch 60 sec demo</button></div></div><div className="orb"><div className="orbInner"><ShieldCheck size={48}/><b>PROTECTED</b><small>by Arbitrum</small></div><span className="floatCard f1"><Truck size={18}/> Delivery verified <Check size={16}/></span><span className="floatCard f2"><CircleDollarSign size={18}/> 2,400 USDG secured</span></div></section><section className="metrics"><div><b>$42,860</b><span>Protected this month</span></div><div><b>98.7%</b><span>Proof approved first time</span></div><div><b>&lt; 2 min</b><span>Settlement time</span></div></section><section className="work"><div className="sectionTitle"><div><span className="eyebrow">YOUR WORKSPACE</span><h2>Protected payments</h2></div><button className="new" onClick={()=>go('create')}><Plus size={17}/> New payment</button></div><div className="jobList">{jobs.map((j,i)=><button className="job" key={j.id} onClick={()=>go(i===0?'fund':i===1?'review':'release')}><div className="avatar">{j.client.slice(0,1)}</div><div className="jobMain"><b>{j.client}</b><span>{j.id} · {j.milestone}</span></div><div className="jobStatus"><span className={'pill p'+i}>{j.status}</span><small>{j.due}</small></div><b className="amount">${j.amount}<small> USDG</small></b><ChevronRight size={19}/></button>)}</div></section></main></>}
function Create(){const [sent,setSent]=useState(false); return <Shell eyebrow="NEW PROTECTED PAYMENT" title="Set the work. Lock the terms." copy="Both parties see the same agreement. Funds remain in non-custodial escrow until delivery is verified."><Progress step={0}/><div className="twoCol"><section className="formCard"><label>Supplier or freelancer<input defaultValue="Kora Foods Ltd."/></label><label>What are you paying for?<input defaultValue="Temperature-controlled produce delivery"/></label><div className="split"><label>Payment amount<input defaultValue="2,400"/></label><label>Currency<select defaultValue="USDG"><option>USDG</option></select></label></div><label>Delivery deadline<input defaultValue="September 23, 2026 · 15:00 WAT"/></label><label>Proof required<textarea defaultValue="GPS-stamped delivery photos, receiver signature, and temperature log."/></label><button className="primary full" onClick={()=>setSent(true)}>Review agreement <ArrowRight size={17}/></button></section><aside className="note"><FileCheck2/><h3>Clear before cash</h3><p>Every payment has a shared, immutable scope and proof checklist. No vague promises. No “he said, she said.”</p><span><ShieldCheck size={16}/> Agreement hash recorded on Arbitrum</span></aside></div>{sent&&<Action title="Agreement drafted" detail="The shared agreement is ready to review and sign." next="Continue to funding" to="fund"/>}</Shell>}
function Fund(){const [open,setOpen]=useState(false);return <Shell eyebrow="FUND ESCROW" title="Secure $2,400 USDG." copy="You keep control until the delivery evidence meets the agreement."><Progress step={1}/><div className="fundCard"><div className="fundIcon"><LockKeyhole/></div><span className="eyebrow">ARBITRUM ONE · NON-CUSTODIAL ESCROW</span><h2>2,400.00 <small>USDG</small></h2><p>≈ $2,400.00 USD</p><div className="fundRows"><span>Network <b>Arbitrum One <i></i></b></span><span>Gas estimate <b>$0.03</b></span><span>Supplier <b>Kora Foods Ltd.</b></span></div><button className="primary full" onClick={()=>setOpen(true)}>Fund protected payment <LockKeyhole size={17}/></button><small className="under"><ShieldCheck size={14}/> Funds can only be released after your approval</small></div>{open&&<Action title="Transaction submitted" detail="Your USDG is now safely held in FlowGuard escrow on Arbitrum One." next="View delivery workflow" to="proof"/>}</Shell>}
function Proof(){const [upload,setUpload]=useState(false); return <Shell eyebrow="DELIVERY PROOF" title="Show the work happened." copy="Verifiable evidence turns a real-world delivery into a release-ready milestone."><Progress step={2}/><div className="proofGrid"><section className="proofCard"><div className={'drop '+(upload?'loaded':'')} onClick={()=>setUpload(true)}>{upload?<><Check size={32}/><b>3 proof items attached</b><span>GPS, signature & temperature log verified</span></>:<><Plus size={25}/><b>Add delivery evidence</b><span>Photos, document, or signed receipt</span></>}</div><div className="checklist"><b>Required by agreement</b><span><Check/> GPS-stamped delivery photo</span><span><Check/> Receiver signature</span><span><Check/> Cold-chain temperature log</span></div><button className="primary full" disabled={!upload} onClick={()=>go('review')}>Submit for approval <ArrowRight size={17}/></button></section><aside className="proofAside"><span className="eyebrow">WHY IT WORKS</span><h3>Evidence everyone can trust.</h3><p>File fingerprints and timestamps are recorded onchain. The original proof is encrypted and stored privately.</p><div><LockKeyhole/> Private by default</div><div><Clock3/> Timestamped instantly</div></aside></div></Shell>}
function Review(){return <Shell eyebrow="REVIEW DELIVERY" title="Everything checks out." copy="Kora Foods submitted proof for FG-2048. Compare it against the agreement before releasing the escrow."><Progress step={3}/><div className="review"><section><div className="evidence"><div className="photo"><Truck size={40}/><span>DELIVERY CONFIRMED</span></div><div><span className="pill p1">All proof verified</span><h3>Temperature-controlled produce delivery</h3><p>Submitted Sep 21, 14:42 WAT</p><button className="textButton" onClick={()=>go('proof')}>View original evidence <ExternalLink size={15}/></button></div></div><div className="match"><ShieldCheck/><div><b>Agreement match</b><span>All 3 required evidence items meet the agreed terms.</span></div><b>100%</b></div></section><aside className="releaseBox"><span>ESCROW BALANCE</span><h2>2,400 <small>USDG</small></h2><p>Ready to settle to Kora Foods Ltd.</p><button className="primary full" onClick={()=>go('release')}>Release payment <ArrowRight size={17}/></button><button className="secondary full">Raise an issue</button></aside></div></Shell>}
function Release(){const [confirm,setConfirm]=useState(false);return <Shell eyebrow="FINAL APPROVAL" title="Release payment to Kora Foods?" copy="This action transfers 2,400 USDG from escrow directly to the verified supplier."><div className="confirm"><div className="confirmIcon"><CircleDollarSign/></div><h2>2,400 <small>USDG</small></h2><span>to Kora Foods Ltd. · 0x71e…9cA4</span><hr/><p><ShieldCheck size={16}/> Delivery proof recorded and approved</p><button className="primary full" onClick={()=>setConfirm(true)}>Confirm & release USDG <ArrowRight size={17}/></button><button className="cancel" onClick={()=>go('review')}>Back to review</button></div>{confirm&&<Action title="Payment released" detail="2,400 USDG has settled to Kora Foods Ltd. on Arbitrum One." next="Return to workspace" to="dashboard"/>}</Shell>}
function Action({title,detail,next,to}){const [done,setDone]=useState(false);useEffect(()=>{let x=setTimeout(()=>setDone(true),1100);return()=>clearTimeout(x)},[]);return <div className="modal"><div className="action">{done?<div className="success"><Check size={32}/></div>:<LoaderCircle className="spin" size={42}/>}<span className="eyebrow">{done?'ACTION COMPLETE':'PROCESSING ON ARBITRUM'}</span><h2>{title}</h2><p>{detail}</p>{done&&<button className="primary full" onClick={()=>go(to)}>{next}<ArrowRight size={17}/></button>}</div></div>}
function Register(){return <Shell eyebrow="BUILDATHON APPLICATION" title="A high-conviction project, ready to build." copy="Copy the answers below into the Arbitrum Open House Singapore registration form."><div className="application"><Answer q="What will you build?" a="FlowGuard: USDG-powered milestone escrow for real-world commerce. Businesses fund protected payments on Arbitrum; suppliers submit privacy-preserving, GPS-stamped delivery proof; buyers release instantly when terms are met. It makes cross-border trade safer and settlement near-instant."/><Answer q="Existing project URL" a="FlowGuard is being built for the Arbitrum Open House Singapore Buildathon. Add your deployed demo URL here once live."/><Answer q="Referral code" a="Leave blank unless you received a community referral code."/></div></Shell>}
function Answer({q,a}){const [copied,setCopied]=useState(false);return <div className="answer"><span>{q}</span><p>{a}</p><button onClick={()=>{navigator.clipboard?.writeText(a);setCopied(true)}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy answer'}</button></div>}
function App(){const [path,setPath]=useState(location.pathname);useEffect(()=>{let f=()=>setPath(location.pathname);addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);return ({'/':<DashboardV2/>, '/create':<Create/>, '/fund':<Fund/>, '/proof':<Proof/>, '/review':<Review/>, '/release':<Release/>, '/buildathon':<Register/>}[path]||<DashboardV2/>)}createRoot(document.getElementById('root')).render(<App/>);
