import React, {useState} from 'react';
import {BrowserProvider, Contract, formatUnits} from 'ethers';
import {ExternalLink, ShieldCheck, WalletCards} from 'lucide-react';

const chain={chainId:'0x66eee',chainName:'Arbitrum Sepolia',nativeCurrency:{name:'Ethereum',symbol:'ETH',decimals:18},rpcUrls:['https://sepolia-rollup.arbitrum.io/rpc'],blockExplorerUrls:['https://sepolia.arbiscan.io']};
const usdg='0xFFC95faa3d63Cde504a05B567C600B78C0b41892';
const abi=['function balanceOf(address) view returns (uint256)','function decimals() view returns (uint8)'];
const deployed=import.meta.env.VITE_FLOWGUARD_CONTRACT_ADDRESS || '';

export default function Testnet(){const [account,setAccount]=useState('');const [balance,setBalance]=useState('');const [message,setMessage]=useState('');const connect=async()=>{if(!window.ethereum){setMessage('Install MetaMask to connect a test wallet.');return}try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:chain.chainId}]})}catch(error){if(error.code===4902)await window.ethereum.request({method:'wallet_addEthereumChain',params:[chain]});else{setMessage('Approve the Arbitrum Sepolia network switch in MetaMask.');return}}try{const [address]=await window.ethereum.request({method:'eth_requestAccounts'});setAccount(address);const provider=new BrowserProvider(window.ethereum);const token=new Contract(usdg,abi,provider);const [raw,decimals]=await Promise.all([token.balanceOf(address),token.decimals()]);setBalance(formatUnits(raw,decimals));setMessage('Wallet connected to Arbitrum Sepolia.')}catch{setMessage('Wallet connection was cancelled or unavailable.')}};return <><div className="betaBar">TESTNET BETA · ARBITRUM SEPOLIA · TEST TOKENS ONLY</div><main className="page"><div className="pageHeading"><span className="eyebrow">PUBLIC TESTNET BETA</span><h1>Use FlowGuard safely on testnet.</h1><p>Connect a test-only wallet. This beta accepts no real assets and uses Paxos test USDG.</p></div><div className="testnetGrid"><section className="testnetCard"><span className="eyebrow">WALLET</span><h2>{account?'Connected':'Not connected'}</h2><p>{account||'Connect MetaMask to inspect the official Paxos test USDG balance.'}</p>{account&&<b className="testBalance">{balance||'0'} <small>test USDG</small></b>}<button className="primary full" onClick={connect}><WalletCards size={17}/>{account?'Refresh wallet':'Connect MetaMask'}</button>{message&&<p className="testMessage">{message}</p>}</section><section className="testnetCard"><span className="eyebrow">ONCHAIN DETAILS</span><div className="networkRows"><span>Network <b>Arbitrum Sepolia · 421614</b></span><span>USDG <a href={`https://sepolia.arbiscan.io/token/${usdg}`} target="_blank" rel="noreferrer">Official test token <ExternalLink size={13}/></a></span><span>Protocol {deployed?<a href={`https://sepolia.arbiscan.io/address/${deployed}`} target="_blank" rel="noreferrer">View contract <ExternalLink size={13}/></a>:<b className="pending">Deployment pending</b>}</span></div></section><section className="testnetCard wide"><ShieldCheck size={28}/><h2>Judge-ready user journey</h2><p>Buyer funds a delivery deal with test USDG. Supplier anchors an encrypted proof hash. Courier and receiver attest to the same proof. Buyer releases settlement. Every live action will show its Arbiscan receipt.</p><div className="roles"><span>Buyer funds</span><span>Supplier submits proof</span><span>Courier attests</span><span>Receiver attests</span><span>Buyer releases</span></div></section></div></main></>}
